[package]
name = "cc_extactor_bindings-sys"
version = "0.1.0"
authors = ["aarno"]
edition = "2018"
links = "ccextractor"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build_dependencies]
cmake = "0.1.45"
bindgen = "0.21.2"
